//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducePricingFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchTracker
    {
        public string ipAddress { get; set; }
        public System.DateTime searchDate { get; set; }
        public int marketSearchID { get; set; }
        public string marketName { get; set; }
        public string commName { get; set; }
        public string packageDesc { get; set; }
        public string itemSizeDesc { get; set; }
        public string varietyName { get; set; }
    }
}
