//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducePricingFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMarketTable
    {
        public string commName { get; set; }
        public string cityName { get; set; }
        public string organic { get; set; }
        public string packageDesc { get; set; }
        public string varietyName { get; set; }
        public string subvarName { get; set; }
        public string gradeDesc { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
        public Nullable<decimal> lowPriceMin { get; set; }
        public Nullable<decimal> highPriceMax { get; set; }
        public Nullable<decimal> mostlyLowMin { get; set; }
        public Nullable<decimal> mostlyHighMax { get; set; }
        public string originName { get; set; }
        public string districtName { get; set; }
        public string itemSizeDesc { get; set; }
        public string color { get; set; }
        public string envDesc { get; set; }
        public string unitSale { get; set; }
        public string quality { get; set; }
        public string condition { get; set; }
        public string appearance { get; set; }
        public string storage { get; set; }
        public string crop { get; set; }
        public string rePack { get; set; }
        public string transmode { get; set; }
        public string offerings { get; set; }
        public string marketTone { get; set; }
        public string priceComment { get; set; }
        public string comment { get; set; }
        public int tMarketID { get; set; }
        public Nullable<System.DateTime> recordCreateDate { get; set; }
    }
}
